<div class="container liq template_600x500">
    <div class="list">
        <div class="search">
            <h3>Add Items and Search for your deal</h3>
            <input type="text" id="items" placeholder="Ex: cheese,milk"/>
            <button type="submit" class="search-btn">Find Deals</button>
            <div class="badge">Get offers | Total: <span>0</span></div>
        </div>
        <div class="gallery-view">
            <div class="loading-indicator hidden">
                <img width="32" height="32" src="http://cdn.cpnscdn.com/static.coupons.com/Sites/img/bigblue/spinner.gif">
            </div>
            <div class="gallery">
            </div>
        </div>
    </div>
    <div class="brands">
        <h3>Our Suggested Brands</h3>
    </div>
</div>
<!-- Load script  "js/main.js" as our entry point -->
<script data-main="frontend/js/main" src="frontend/js/lib/require.js"></script>